# This is a basic workflow to help you get started with Actions

name: Generate Html

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # [pull_request_target]
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build" 
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write
      pages: write
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Install Asciidoctor 
        run: |
          sudo gem install asciidoctor
      
      - name: Generate HTML
        run: |
          asciidoctor -o $GITHUB_WORKSPACE/output.html README.adoc 
      # Runs a single command using the runners shell
      #- name: asciidoctor-ghpages
      #  uses: manoelcampos/asciidoctor-ghpages-action@v2
      #  with:
      #    pdf_build: true
      #    asciidoctor_params: --attribute=nofooter
      - name: Move HTML to Repository
        run: |
          mv $GITHUB_WORKSPACE/output.html $GITHUB_WORKSPACE/generated/output.html
      
      - name: Commit HTML
        run: 
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add generated/output.html
          git diff-index --quiet HEAD || git commit -m "Generate HTML from AsciiDoc" && git push